version: '3.3'

services:

    db:
      image: mongo:latest
      restart: always
      expose:
        - 27019
      ports:
        - "27019:27017"
      networks:
        - db-net
      environment:
        #- MONGO_INITDB_DATABASE=admin
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admcacem}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-Cacem972}   
      volumes:
        - ./data/mongod.conf:/etc/mongod.conf
        - ./data/mongo/data:/data/db

    phasme2web:
      container_name: ${HOSTNAME:-vvdecha-smb}
      build:
        context: ./sssd/
        dockerfile: Dockerfile.deb11
      hostname: ${HOSTNAME:-vvdecha-smb}
      extra_hosts:
        - ${HOSTNAME:-vvdecha-smb}.${DOMAIN_NAME:-agglo.local} ${HOSTNAME:-vvdecha-smb}:${IP_ADDRESS}
      expose:
        - 3030
        - 80
        - 443
      ports:
        - "137:137"
        - "138:138"
        - "139:139"
        - "4445:445"
        - "443:443"
        - "80:80"
        - "3030:3030"
      networks:
        - db-net
      depends_on:
        - "db"
      #links:
      #  - "db"
      environment:
        - TZ=${TZ:-America/Martinique}
        - IP_ADDRESS=${IP_ADDRESS:-172.30.128.182}
        - DOMAIN_NAME=${DOMAIN_NAME:-agglo.local}
        - ADMIN_SERVER=${ADMIN_SERVER:-dc11.agglo.local}
        - MONGODB_URL=${MONGODB_URL:-mongodb://admcacem:Cacem972@db:27017/cacemdb?authSource=admin}
        - MONGO_BASENAME=${MONGO_BASENAME:-cacemdb}
        - WORKGROUP=${WORKGROUP:-agglo}
        - AD_USERNAME=${AD_USERNAME:-hdechavignyadm}
        - AD_PASSWORD=${AD_PASSWORD:-d@nZel!77}
        - CHOKIDAR_USEPOLLING=true
      volumes:
        - ./srv:/srv:rw
        - ./client/www:/www
        - /srv/node_modules
   
    mongo-express:
      image: mongo-express
      restart: always
      expose:
        - 8081
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME:-admcacem}
        - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD:-Cacem972}
        - ME_CONFIG_MONGODB_URL=${MONGODB_URL:-mongodb://admcacem:Cacem972@db:27017/cacemdb?authSource=admin}
      depends_on:
        - db    
      networks:
        - db-net   

    #quasar-app:
    #  container_name: docker-q-app
    #  build:
    #    context: ./client
    #    dockerfile: Dockerfile
    #  volumes:
    #    - './client:/usr/src/app'
    #    - '/usr/src/app/node_modules'
    #  expose:
    #    - 8080
    #  environment:
    #    - CHOKIDAR_USEPOLLING=true
    #  ports: 
    #    - "8080:8080"
    #  depends_on:
    #    - mongo
    #  networks:
    #    - db-net

volumes:
  app:
  #nodemodules: {}

networks:
  db-net: